### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by gausby** [KoldskaalsConf/koldskaalsconf#1]
We need a logo. Something-something + koldskål + hexagon.

**Comment by Tenzer** [comment]
I think a motive like [this](https://www.flickr.com/photos/skg/4540538420/) could work as a logo, and would probably also work in black and white.

**Comment by gausby** [comment]
Could work. @mafintosh said he would attempt something

**Comment by gausby** [comment]
Ole made a logo for the conference.

![koldskaal](https://cloud.githubusercontent.com/assets/482052/8033246/0cf01a44-0ddd-11e5-8ab7-2fb3b9c24507.png)

It is really neat!
