### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by gausby** [KoldskaalsConf/koldskaalsconf#2]
We need a website with info.

We also need to generate some info.

**Comment by kevinsimper** [comment]
@gausby What kind of conference is koldskaalsconf?

**Comment by gausby** [comment]
@kevinsimper it's a single day, single track tech conference. Aims to be more fun than serious. Think of it as an informal meet up where the talks are focused on topics such as cryptography or weird and funny stuff, most likely done with a computer, and everyone is encouraged to bring and enjoy some koldskål.

**Comment by kevinsimper** [comment]
That sounds fun, but should be rather soon if you would like there to be koldskål? :)

**Comment by Tenzer** [comment]
It's scheduled for 22nd of August, as per #5.

**Comment by gausby** [comment]
@Tenzer true, it will happen on August 22.

@kevinsimper the Koldskåls season is January 1 through December 31 ;)

**Comment by kevinsimper** [comment]
Okay, back to website, should a pull request be put against this repository, or add another for website called for example `website`, like nodejs does?

**Comment by gausby** [comment]
I can create a project on this organisation and give you access to it, if you want to give it a go :)

**Comment by kevinsimper** [comment]
Yes, please! :)

**Comment by gausby** [comment]
:+1: You are invited!
