### ISSUE TITLE
Venue

### ISSUE THREAD

**Issue by gausby** [KoldskaalsConf/koldskaalsconf#3]
This might sound stupid, but should we rent a boat?

**Comment by Tenzer** [comment]
What kind of boat? Something like [this](http://www.hottug.nl/index_en.html)?

**Comment by gausby** [comment]
@Tenzer I don't think it will be big enough; we would need a fleet.

We might have to choose a park for the venue, which would mean we are betting on the weather to be good. Alternatively we could have it at a barn or something, or a concert venue.

The keyword here is free. I don't wanna deal with money.

**Comment by gausby** [comment]
We might be able to have it at KU; this needs to be confirmed though.

**Comment by max-mapper** [comment]
for TacoConf we visited 3 different taquerias, each one specialized in a different kind of taco. This format requires bicycles to work well. One of the venues was suitable for presentations so we did a block of short talks there in the middle of the day. This gave ample time for people to socialize

**Comment by gausby** [comment]
The idea of going to a couple of places are good, but I have som thoughts.

For some reason we do not sell Koldskål in stands, even though it would sell like koldskål on a hot summer day. I don't know, we are not good sales people. Also, we have to bet on the weather being good if we wanna do the conference outside.

We could have some pre meet-up session where we bike from somewhere to the university where the conference could take place—this seems like the best of both worlds :)
