### ISSUE TITLE
Call for Papers

### ISSUE THREAD

**Issue by gausby** [KoldskaalsConf/koldskaalsconf#4]
We need to get a final confirmation from the possible speakers we have spoken to so far; And we might want to get a few extra ideas for talks.

We need: Mad science computer science, something with crypto, something with koldskål.

**Comment by Tenzer** [comment]
I would like to hear about how to reverse engineer a koldskål recipe.

**Comment by gausby** [comment]
@Tenzer It should be possible. I don't know if that is possible.

**Comment by gausby** [comment]
We got a speaker, the title of the talk will be: "Fully homomorphic encryption: The Swiss army knife of cryptography"
